# Generated by Django 5.1.2 on 2026-02-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magical_wishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivewish',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
