# Generated by Django 5.1.2 on 2026-02-10 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdaywish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaywish',
            name='template_name',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='birthdaywish',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wishimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
